trigger:
- main
  
# pr:
#   branches:
#     include:
#       - dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'


    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'testconnection'
        repository: 'azurepipeline-python'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'