jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-16.04' # other options: 'macOS-10.14', 'vs2017-win2016'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'

- stage: test
  displayName: Test
  dependsOn:
  - build
  jobs:
  - job: test_python_solution
    displayName: test python solution
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python $(python.version)'
        inputs:
          versionSpec: '$(python.version)'
      - script: |
          python -m pip install flake8
          flake8 .
        displayName: 'Run lint tests'