variables:
  python.version: "Latest"

trigger:
- main

stages:
- stage: build
  displayName: Build
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: 'Test'
    displayName: build solution  
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
      displayName: 'Run a multi-line script'

- stage: test
  displayName: Test
  dependsOn:
  - build
  jobs:
  - job: test_python_solution
    displayName: test python solution
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python $(python.version)'
        inputs:
          versionSpec: '$(python.version)'
      - script: |
          python -m pip install flake8
          flake8 .
        displayName: 'Run lint tests'