trigger:
- main
  
# pr:
#   branches:
#     include:
#       - dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'


    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'testconnection'
        repository: 'azurepipeline-python'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

- stage: Deploy
  displayName: Deploy Helm
  jobs:  
  - job: Deploy
    displayName: Deploy Helm
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: 'azure-pipeline-connection'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: 'helm'
        valueFile: 'helm/values.yaml'
        releaseName: azurepipeline-trial
        arguments: '--namespace test'
        # arguments: '--install -f values.yaml azurepipeline-trial .'
        # arguments: 'azure-pipeline-trial helm/ -f values.yaml --namespace default ./'
        # arguments: '--install azurepipeline-trial --values values.yaml helm/values.yaml'