trigger:
- main

stages:
- stage: build
  displayName: Build
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: 'Test'
    pool:
    vmImage: 'ubuntu-16.04' # other options: 'macOS-10.14', 'vs2017-win2016'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
    displayName: build solution  
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

- stage: test
  displayName: Test
  dependsOn:
  - build
  jobs:
  - job: test_python_solution
    displayName: test python solution
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: test        