trigger:
- main
  
# pr:
#   branches:
#     include:
#       - dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'


    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'testconnection'
        repository: 'azurepipeline-python'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

- stage: Deploy
  displayName: Deploy Helm
  jobs:  
  - job: Deploy
    displayName: Deploy Helm
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: '3.2.3'

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: 'azure-pipeline-connection'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: 'helm/'
        releaseName: 'azurepipeline-trial'
        # arguments: '--install trial-azure-pipeline -f values.yaml azure-pipeline-trial .'
        arguments: '--set tag=$(tag) --set name=azurepipeline-trial --set namespace=trial-azure-pipeline --install -f values.yaml azure-pipeline-trial'
