variables:
  python.version: "Latest"

trigger:
- main

stages:
- stage: build
  displayName: Build
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: 'Test'
    displayName: build solution  
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
      displayName: 'Run a multi-line script'

- stage: test
  displayName: Test
  dependsOn:
  - build
  jobs:
  - job: test_python_solution
    displayName: test python solution
    steps:
      - task: PythonScript@0
        inputs:
          scriptSource: 'filePath'
          scriptPath: '$(System.DefaultWorkingDirectory)/azurepipeline-python'
      - task: CmdLine@2
        inputs:
          script: 'RUN ls'
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true
          architecture: 'x64'

      # - script: |
      #     python -m pip install flake8
      #     flake8 .
      #   displayName: 'Run lint tests'