apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial
  labels:
    app: trial
spec:
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      serviceAccountName: azure-devops-admin
      containers:
        - name: trial
          image: {{ printf "%s:%s" .Values.image_repo .Values.image_tag }}